services:
  service1:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 5000
        published: 5000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
      - GEMINI_API_KEY=AIzaSyAne5D5MFKo7Qd1Ry44uW8DrnxTAC_1hxg
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
